# Generated by Django 3.2.6 on 2021-08-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('assignedto', models.CharField(max_length=30)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
